import type { Language } from '../types'

type MessageValue = string | ((...args: Array<string | number>) => string)

type CopyDictionary = {
  [key: string]: MessageValue
}

const messages: Record<Language, CopyDictionary> = {
  en: {
    appTitle: 'Agent Designer Simulator',
    localMvp: 'Local MVP V1',
    navDashboard: 'Dashboard',
    navGenerate: 'Generate',
    navWorkspace: 'Workspace',
    navHistory: 'History',
    darkMode: 'Dark mode',
    lightMode: 'Light mode',
    languageEnglish: 'English',
    languageMalay: 'Bahasa Melayu',
    resume: 'Resume',
    noActiveDraft: 'No active draft yet',
    resumeDescription:
      'Start from the Scenario Generator to create a reproducible challenge and begin your first GPRID design.',
    continueDraft: 'Continue Draft',
    generateScenario: 'Generate Scenario',
    recentScores: 'Recent Scores',
    latestAttempts: 'Latest attempts',
    openHistory: 'Open history',
    noAttemptsYet: 'No attempts yet',
    noAttemptsDescription:
      'Finish one scenario to start building local score history and track how your GPRID decisions improve over time.',
    quickStats: 'Progress Dashboard',
    attempts: 'Total Attempts',
    average: 'Average Score',
    best: 'Best Score',
    weakestLayer: 'Weakest Layer',
    mostPlayedDomain: 'Most Played Domain',
    historyBased: 'Based on current local history',
    nextMove: 'Next Move',
    practiceWeakest: 'Practice your weakest layer',
    practiceWeakestDescription: 'Use the generator to create a fresh challenge, then focus on strengthening your {0} decisions inside the workspace.',
    startNewScenario: 'Start New Scenario',
    howToPlay: 'How To Play',
    howToPlayTitle: 'Understand the practice loop',
    howToPlayDescription:
      'Generate a scenario, build all five GPRID layers, submit your design, review the feedback, then retry or start a new challenge.',
    howStep1: '1. Generate a scenario with domain, level, and optional seed.',
    howStep2: '2. Complete Goal, Priority, Rules, Logic, and Decision in order.',
    howStep3: '3. Submit for evaluation and inspect your weakest layer.',
    howStep4: '4. Use history to replay the same seed and compare improvement.',
    tutorialTitle: 'Welcome to your first GPRID simulation',
    tutorialDescription:
      'This short tutorial explains how the MVP works so you can start confidently.',
    tutorialStep1Title: '1. Start With a Scenario',
    tutorialStep1Body:
      'Choose a domain and difficulty, then generate a reproducible challenge using a human-readable seed.',
    tutorialStep2Title: '2. Think in GPRID',
    tutorialStep2Body:
      'Build your design layer by layer: Goal, Priority, Rules, If-Then Logic, and Decision.',
    tutorialStep3Title: '3. Learn From Feedback',
    tutorialStep3Body:
      'Submit your draft to get local rubric feedback, then retry the same seed to improve.',
    tutorialDismiss: 'Got it',
    tutorialOpen: 'Open Tutorial',
    tutorialSkip: 'Skip Tutorial',
    beginnerMode: 'Beginner Mode',
    beginnerModeHint: 'Show guided examples for every GPRID layer.',
    scenarioGenerator: 'Scenario Generator',
    scenarioGeneratorTitle: 'Create a reproducible challenge',
    scenarioGeneratorDescription:
      'Select a launch domain, choose a difficulty, and optionally provide a human-readable seed such as HEALTH-L5-TRIAGE-001.',
    domain: 'Domain',
    difficulty: 'Difficulty',
    seed: 'Seed',
    seedFormatHint: 'Human-readable format: DOMAIN-L{0}-FAMILY-001',
    generatePreview: 'Generate Preview',
    newSeed: 'New Seed',
    startScenario: 'Start Scenario',
    preview: 'Preview',
    difficultyEngine: 'Difficulty Engine',
    objective: 'Objective',
    constraints: 'Constraints',
    risks: 'Risks',
    sampleSituation: 'Sample Situation',
    gpridSpine: 'GPRID Spine',
    gpridTitle: 'Build layer by layer',
    gpridDescription:
      'Each panel unlocks the next one so the framework stays traceable from goal to decision.',
    complete: 'Complete',
    needsWork: 'Needs work',
    pending: 'Pending',
    layerReady: 'Layer is structurally ready for submission.',
    goalDesign: 'Goal Design',
    priorityDesign: 'Priority Design',
    rulesDesign: 'Rules Design',
    logicDesign: 'If-Then Logic',
    decisionOutput: 'Decision Output',
    goalPlaceholder: 'Define one clear, measurable goal.',
    secondaryGoalPlaceholder: 'Optional secondary goal',
    conflictPlaceholder: 'How should the agent resolve conflicts between the top priorities?',
    addRule: 'Add Rule',
    removeRule: 'Remove rule',
    addLogicCard: 'Add Logic Card',
    removeLogicCard: 'Remove logic card',
    ruleReasoningPlaceholder: 'Why does this rule exist?',
    ifPlaceholder: 'IF condition',
    thenPlaceholder: 'THEN action',
    becausePlaceholder: 'BECAUSE reasoning',
    elsePlaceholder: 'ELSE branch',
    coordinationPlaceholder: 'Agent coordination note',
    decisionStatementPlaceholder: 'State the final decision for the sample situation',
    decisionReasoningPlaceholder:
      'Explain how the decision follows from your goal, priorities, rules, and logic.',
    lowConfidence: 'Low confidence',
    mediumConfidence: 'Medium confidence',
    highConfidence: 'High confidence',
    markGoalComplete: 'Mark Goal Complete',
    markPriorityComplete: 'Mark Priority Complete',
    markRulesComplete: 'Mark Rules Complete',
    markLogicComplete: 'Mark Logic Complete',
    markDecisionComplete: 'Mark Decision Complete',
    submitForEvaluation: 'Submit for Evaluation',
    beginnerExamples: 'Beginner Examples',
    beginnerGoal: 'Example Goal',
    beginnerPriority: 'Example Priority',
    beginnerRules: 'Example Rules',
    beginnerLogic: 'Example If-Then',
    beginnerDecision: 'Example Decision',
    evaluation: 'Evaluation',
    overallScore: 'Overall Score',
    layerBreakdown: 'Layer Breakdown',
    strengths: 'Strengths',
    weaknesses: 'Weaknesses',
    blindSpots: 'Blind Spots',
    expertRecommendation: 'Expert Recommendation',
    weakestLayerLabel: 'Weakest layer: {0}',
    comparison: 'Comparison',
    previous: '{0} previous',
    pointsDelta: '{0} points',
    comparisonHint: 'Comparing this seed against your most recent prior attempt.',
    blockingIssues: '{0} blocking issues',
    coachingNotes: '{0} coaching notes',
    retrySeed: 'Retry Seed',
    openWorkspace: 'Open Workspace',
    viewHistory: 'View History',
    history: 'History',
    historyTitle: 'Local attempt record',
    historyDescription:
      'Review completed attempts, filter by seed and difficulty, and replay any scenario locally without backend dependencies.',
    seedSearch: 'Seed search',
    allDomains: 'All domains',
    allLevels: 'All levels',
    noMatchingAttempts: 'No matching attempts',
    noMatchingAttemptsDescription:
      'Adjust the filters or complete a new scenario to expand your local score history.',
    viewEvaluation: 'View Evaluation',
    retryFromSeed: 'Retry from Seed',
    tutorialBanner: 'New here? Start the quick tutorial and turn on Beginner Mode for guided examples.',
    openHowToPlay: 'See How To Play',
    finishLayer: 'Complete the required fields in {0} before marking it finished.',
    layerMarked: 'Layer {0} marked complete.',
    submitFinishAll: 'Finish and mark all five layers before submitting.',
    resolveValidation: 'Resolve the remaining validation issues in {0} before submitting.',
    firstTimeBannerTitle: 'First-time onboarding',
    firstTimeBannerDescription:
      'Use the tutorial and Beginner Mode to understand the game loop before your first attempt.',
    deepseekJudge: 'DeepSeek AI Judge',
    deepseekJudgeTitle: 'Advanced AI evaluation',
    deepseekJudgeDescription:
      'Run an optional DeepSeek judging pass on top of the local rubric to get competition-style critique.',
    runDeepSeekJudge: 'Run DeepSeek Judge',
    deepseekLoading: 'DeepSeek is evaluating this submission...',
    deepseekRetry: 'Retry DeepSeek Judge',
    deepseekHistory: 'AI Judge History',
    noDeepSeekHistory: 'No DeepSeek evaluations yet for this attempt.',
    deepseekImprovements: 'Improvements',
    deepseekTopTeam: 'How a Top Team Would Improve This',
    deepseekModel: 'Model',
    deepseekOverall: 'AI Overall',
    deepseekOptional: 'Optional advanced layer',
    deepseekErrorPrefix: 'DeepSeek error:',
    deepseekDebug: 'DeepSeek Debug',
    deepseekRawApi: 'Raw API Response',
    deepseekRawParsed: 'Parsed Response',
    deepseekFinalUi: 'Final UI Values',
    deepseekConsistency: 'Consistency Check',
    journeyTitle: 'POLYCC Agentic AI League Journey',
    journeyDescription:
      'Use this section to understand where you are in the competition journey today, what is officially confirmed, what is only a reasonable assumption, and what is still unknown.',
    officiallyConfirmed: 'Officially Confirmed',
    reasonableAssumptions: 'Reasonable Assumptions',
    unknownInformation: 'Unknown Information',
    focusTodayLabel: 'What To Focus On Today',
    noConfirmedInfo: 'No confirmed information is listed for this item.',
    noAssumptionsInfo: 'No assumptions are included in this guide. Only official information is used.',
    noUnknownInfo: 'No unknown information is listed for this item.',
  },
  ms: {
    appTitle: 'Simulator Pereka Ejen',
    localMvp: 'MVP Tempatan V1',
    navDashboard: 'Papan Pemuka',
    navGenerate: 'Jana',
    navWorkspace: 'Ruang Kerja',
    navHistory: 'Sejarah',
    darkMode: 'Mod gelap',
    lightMode: 'Mod cerah',
    languageEnglish: 'English',
    languageMalay: 'Bahasa Melayu',
    resume: 'Sambung',
    noActiveDraft: 'Tiada draf aktif lagi',
    resumeDescription:
      'Mulakan dari Penjana Senario untuk mencipta cabaran yang boleh diulang dan memulakan reka bentuk GPRID pertama anda.',
    continueDraft: 'Sambung Draf',
    generateScenario: 'Jana Senario',
    recentScores: 'Skor Terkini',
    latestAttempts: 'Percubaan terkini',
    openHistory: 'Buka sejarah',
    noAttemptsYet: 'Belum ada percubaan',
    noAttemptsDescription:
      'Selesaikan satu senario untuk mula membina sejarah skor tempatan dan melihat peningkatan keputusan GPRID anda dari semasa ke semasa.',
    quickStats: 'Papan Kemajuan',
    attempts: 'Jumlah Percubaan',
    average: 'Purata Skor',
    best: 'Skor Terbaik',
    weakestLayer: 'Lapisan Paling Lemah',
    mostPlayedDomain: 'Domain Paling Kerap',
    historyBased: 'Berdasarkan sejarah tempatan semasa',
    nextMove: 'Langkah Seterusnya',
    practiceWeakest: 'Latih lapisan paling lemah',
    practiceWeakestDescription: 'Gunakan penjana untuk mencipta cabaran baharu, kemudian fokus mengukuhkan keputusan {0} anda di ruang kerja.',
    startNewScenario: 'Mulakan Senario Baharu',
    howToPlay: 'Cara Bermain',
    howToPlayTitle: 'Fahami kitaran latihan',
    howToPlayDescription:
      'Jana satu senario, bina kelima-lima lapisan GPRID, hantar reka bentuk anda, semak maklum balas, kemudian cuba semula atau mulakan cabaran baharu.',
    howStep1: '1. Jana senario dengan domain, tahap, dan seed pilihan.',
    howStep2: '2. Lengkapkan Goal, Priority, Rules, Logic, dan Decision mengikut turutan.',
    howStep3: '3. Hantar untuk penilaian dan lihat lapisan paling lemah anda.',
    howStep4: '4. Gunakan sejarah untuk ulang seed yang sama dan bandingkan peningkatan.',
    tutorialTitle: 'Selamat datang ke simulasi GPRID pertama anda',
    tutorialDescription:
      'Tutorial ringkas ini menerangkan cara MVP berfungsi supaya anda boleh bermula dengan yakin.',
    tutorialStep1Title: '1. Mulakan Dengan Senario',
    tutorialStep1Body:
      'Pilih domain dan kesukaran, kemudian jana cabaran yang boleh diulang menggunakan seed yang mudah dibaca.',
    tutorialStep2Title: '2. Fikir Dalam GPRID',
    tutorialStep2Body:
      'Bina reka bentuk anda lapisan demi lapisan: Goal, Priority, Rules, If-Then Logic, dan Decision.',
    tutorialStep3Title: '3. Belajar Daripada Maklum Balas',
    tutorialStep3Body:
      'Hantar draf anda untuk mendapatkan maklum balas rubrik tempatan, kemudian cuba semula seed yang sama untuk meningkatkan prestasi.',
    tutorialDismiss: 'Faham',
    tutorialOpen: 'Buka Tutorial',
    tutorialSkip: 'Langkau Tutorial',
    beginnerMode: 'Mod Beginner',
    beginnerModeHint: 'Tunjukkan contoh berpandu untuk setiap lapisan GPRID.',
    scenarioGenerator: 'Penjana Senario',
    scenarioGeneratorTitle: 'Cipta cabaran yang boleh diulang',
    scenarioGeneratorDescription:
      'Pilih domain pelancaran, pilih tahap kesukaran, dan masukkan seed mudah dibaca seperti HEALTH-L5-TRIAGE-001 jika mahu.',
    domain: 'Domain',
    difficulty: 'Kesukaran',
    seed: 'Seed',
    seedFormatHint: 'Format mudah dibaca: DOMAIN-L{0}-FAMILY-001',
    generatePreview: 'Jana Pratonton',
    newSeed: 'Seed Baharu',
    startScenario: 'Mula Senario',
    preview: 'Pratonton',
    difficultyEngine: 'Enjin Kesukaran',
    objective: 'Objektif',
    constraints: 'Kekangan',
    risks: 'Risiko',
    sampleSituation: 'Situasi Contoh',
    gpridSpine: 'Tulang Belakang GPRID',
    gpridTitle: 'Bina satu demi satu',
    gpridDescription:
      'Setiap panel membuka panel seterusnya supaya rangka kerja kekal boleh dijejak dari goal hingga keputusan.',
    complete: 'Selesai',
    needsWork: 'Perlu dibaiki',
    pending: 'Belum selesai',
    layerReady: 'Lapisan ini sedia secara struktur untuk dihantar.',
    goalDesign: 'Reka Bentuk Goal',
    priorityDesign: 'Reka Bentuk Priority',
    rulesDesign: 'Reka Bentuk Rules',
    logicDesign: 'If-Then Logic',
    decisionOutput: 'Keputusan Akhir',
    goalPlaceholder: 'Takrifkan satu goal yang jelas dan boleh diukur.',
    secondaryGoalPlaceholder: 'Goal kedua pilihan',
    conflictPlaceholder: 'Bagaimana ejen patut menyelesaikan konflik antara priority teratas?',
    addRule: 'Tambah Rule',
    removeRule: 'Buang rule',
    addLogicCard: 'Tambah Kad Logic',
    removeLogicCard: 'Buang kad logic',
    ruleReasoningPlaceholder: 'Mengapa rule ini wujud?',
    ifPlaceholder: 'Keadaan IF',
    thenPlaceholder: 'Tindakan THEN',
    becausePlaceholder: 'Rasional BECAUSE',
    elsePlaceholder: 'Cabang ELSE',
    coordinationPlaceholder: 'Nota koordinasi ejen',
    decisionStatementPlaceholder: 'Nyatakan keputusan akhir untuk situasi contoh',
    decisionReasoningPlaceholder:
      'Terangkan bagaimana keputusan ini mengikuti goal, priority, rules, dan logic anda.',
    lowConfidence: 'Keyakinan rendah',
    mediumConfidence: 'Keyakinan sederhana',
    highConfidence: 'Keyakinan tinggi',
    markGoalComplete: 'Tanda Goal Selesai',
    markPriorityComplete: 'Tanda Priority Selesai',
    markRulesComplete: 'Tanda Rules Selesai',
    markLogicComplete: 'Tanda Logic Selesai',
    markDecisionComplete: 'Tanda Decision Selesai',
    submitForEvaluation: 'Hantar Untuk Penilaian',
    beginnerExamples: 'Contoh Beginner',
    beginnerGoal: 'Contoh Goal',
    beginnerPriority: 'Contoh Priority',
    beginnerRules: 'Contoh Rules',
    beginnerLogic: 'Contoh If-Then',
    beginnerDecision: 'Contoh Decision',
    evaluation: 'Penilaian',
    overallScore: 'Skor Keseluruhan',
    layerBreakdown: 'Pecahan Lapisan',
    strengths: 'Kekuatan',
    weaknesses: 'Kelemahan',
    blindSpots: 'Blind Spots',
    expertRecommendation: 'Cadangan Pakar',
    weakestLayerLabel: 'Lapisan paling lemah: {0}',
    comparison: 'Perbandingan',
    previous: '{0} sebelumnya',
    pointsDelta: '{0} mata',
    comparisonHint: 'Membandingkan seed ini dengan percubaan terdahulu yang paling terkini.',
    blockingIssues: '{0} isu kritikal',
    coachingNotes: '{0} nota bimbingan',
    retrySeed: 'Cuba Semula Seed',
    openWorkspace: 'Buka Ruang Kerja',
    viewHistory: 'Lihat Sejarah',
    history: 'Sejarah',
    historyTitle: 'Rekod percubaan tempatan',
    historyDescription:
      'Semak percubaan yang telah diselesaikan, tapis mengikut seed dan kesukaran, dan ulang mana-mana senario secara tempatan tanpa backend.',
    seedSearch: 'Carian seed',
    allDomains: 'Semua domain',
    allLevels: 'Semua tahap',
    noMatchingAttempts: 'Tiada percubaan sepadan',
    noMatchingAttemptsDescription:
      'Laraskan penapis atau selesaikan senario baharu untuk menambah sejarah skor tempatan anda.',
    viewEvaluation: 'Lihat Penilaian',
    retryFromSeed: 'Ulang Dari Seed',
    tutorialBanner: 'Baru di sini? Mulakan tutorial ringkas dan hidupkan Mod Beginner untuk contoh berpandu.',
    openHowToPlay: 'Lihat Cara Bermain',
    finishLayer: 'Lengkapkan medan yang diperlukan dalam {0} sebelum menandakan ia selesai.',
    layerMarked: 'Lapisan {0} telah ditandakan selesai.',
    submitFinishAll: 'Lengkapkan dan tandakan semua lima lapisan sebelum menghantar.',
    resolveValidation: 'Selesaikan isu validasi yang masih ada dalam {0} sebelum menghantar.',
    firstTimeBannerTitle: 'Onboarding kali pertama',
    firstTimeBannerDescription:
      'Gunakan tutorial dan Mod Beginner untuk memahami aliran permainan sebelum percubaan pertama anda.',
    deepseekJudge: 'Juri AI DeepSeek',
    deepseekJudgeTitle: 'Penilaian AI lanjutan',
    deepseekJudgeDescription:
      'Jalankan penilaian DeepSeek pilihan di atas rubrik tempatan untuk mendapatkan kritikan gaya pertandingan.',
    runDeepSeekJudge: 'Jalankan Juri DeepSeek',
    deepseekLoading: 'DeepSeek sedang menilai penghantaran ini...',
    deepseekRetry: 'Cuba Semula Juri DeepSeek',
    deepseekHistory: 'Sejarah Juri AI',
    noDeepSeekHistory: 'Belum ada penilaian DeepSeek untuk percubaan ini.',
    deepseekImprovements: 'Penambahbaikan',
    deepseekTopTeam: 'Bagaimana Pasukan Terbaik Akan Memperbaiki Ini',
    deepseekModel: 'Model',
    deepseekOverall: 'Keseluruhan AI',
    deepseekOptional: 'Lapisan lanjutan pilihan',
    deepseekErrorPrefix: 'Ralat DeepSeek:',
    deepseekDebug: 'Debug DeepSeek',
    deepseekRawApi: 'Respons API Mentah',
    deepseekRawParsed: 'Respons Diparse',
    deepseekFinalUi: 'Nilai UI Akhir',
    deepseekConsistency: 'Semakan Konsistensi',
    journeyTitle: 'Perjalanan POLYCC Agentic AI League',
    journeyDescription:
      'Gunakan seksyen ini untuk memahami di mana kedudukan anda dalam perjalanan pertandingan hari ini, apa yang disahkan secara rasmi, apa yang hanya andaian munasabah, dan apa yang masih belum diketahui.',
    officiallyConfirmed: 'Disahkan Secara Rasmi',
    reasonableAssumptions: 'Andaian Munasabah',
    unknownInformation: 'Maklumat Belum Diketahui',
    focusTodayLabel: 'Fokus Hari Ini',
    noConfirmedInfo: 'Tiada maklumat disahkan disenaraikan untuk item ini.',
    noAssumptionsInfo: 'Tiada andaian dimasukkan dalam panduan ini. Hanya maklumat rasmi digunakan.',
    noUnknownInfo: 'Tiada maklumat belum diketahui disenaraikan untuk item ini.',
  },
}

export const t = (
  language: Language,
  key: string,
  ...args: Array<string | number>
): string => {
  const value = messages[language][key] ?? messages.en[key] ?? key
  const base = typeof value === 'function' ? value(...args) : String(value)
  return args.reduce<string>(
    (output, arg, index) => output.split(`{${index}}`).join(String(arg)),
    base,
  )
}
