import type { Language } from '../types'

type MessageValue = string | ((...args: Array<string | number>) => string)

type CopyDictionary = {
  [key: string]: MessageValue
}

const messages: Record<Language, CopyDictionary> = {
  en: {
    appTitle: 'Agent Designer Simulator',
    localMvp: 'Local MVP V1',
    navDashboard: 'Dashboard',
    navGenerate: 'Generate',
    navWorkspace: 'Training Workspace',
    navHistory: 'History',
    darkMode: 'Dark mode',
    lightMode: 'Light mode',
    languageEnglish: 'English',
    languageMalay: 'Bahasa Melayu',
    resume: 'Resume',
    noActiveDraft: 'No active draft yet',
    resumeDescription:
      'Start from the Scenario Generator to create a reproducible challenge and begin your first GPRID design.',
    continueDraft: 'Continue Draft',
    generateScenario: 'Generate Scenario',
    recentScores: 'Recent Scores',
    latestAttempts: 'Latest attempts',
    openHistory: 'Open history',
    noAttemptsYet: 'No attempts yet',
    noAttemptsDescription:
      'Finish one scenario to start building local score history and track how your GPRID decisions improve over time.',
    quickStats: 'Progress Dashboard',
    attempts: 'Total Attempts',
    average: 'Average Score',
    best: 'Best Score',
    weakestLayer: 'Weakest Layer',
    mostPlayedDomain: 'Most Played Domain',
    historyBased: 'Based on current local history',
    nextMove: 'Next Move',
    practiceWeakest: 'Practice your weakest layer',
    practiceWeakestDescription: 'Use the generator to create a fresh challenge, then focus on strengthening your {0} decisions inside the workspace.',
    startNewScenario: 'Start New Scenario',
    howToPlay: 'How To Play',
    howToPlayTitle: 'Understand the practice loop',
    howToPlayDescription:
      'Generate a scenario, build all five GPRID layers, submit your design, review the feedback, then retry or start a new challenge.',
    howStep1: '1. Generate a scenario with domain, level, and optional seed.',
    howStep2: '2. Complete Goal, Priority, Rules, Logic, and Decision in order.',
    howStep3: '3. Submit for evaluation and inspect your weakest layer.',
    howStep4: '4. Use history to replay the same seed and compare improvement.',
    tutorialTitle: 'Welcome to your first GPRID simulation',
    tutorialDescription:
      'This short tutorial explains how the MVP works so you can start confidently.',
    tutorialStep1Title: '1. Start With a Scenario',
    tutorialStep1Body:
      'Choose a domain and difficulty, then generate a reproducible challenge using a human-readable seed.',
    tutorialStep2Title: '2. Think in GPRID',
    tutorialStep2Body:
      'Build your design layer by layer: Goal, Priority, Rules, If-Then Logic, and Decision.',
    tutorialStep3Title: '3. Learn From Feedback',
    tutorialStep3Body:
      'Submit your draft to get local rubric feedback, then retry the same seed to improve.',
    tutorialDismiss: 'Got it',
    tutorialOpen: 'Open Tutorial',
    tutorialSkip: 'Skip Tutorial',
    beginnerMode: 'Beginner Mode',
    beginnerModeHint: 'Show guided examples for every GPRID layer.',
    scenarioGenerator: 'Scenario Generator',
    scenarioGeneratorTitle: 'Create a reproducible challenge',
    scenarioGeneratorDescription:
      'Select a launch domain, choose a difficulty, and optionally provide a human-readable seed such as HEALTH-L5-TRIAGE-001.',
    domain: 'Domain',
    difficulty: 'Difficulty',
    seed: 'Training Code',
    seedFormatHint: 'Human-readable format: DOMAIN-L{0}-FAMILY-001',
    generatePreview: 'Generate Preview',
    newSeed: 'New Seed',
    startScenario: 'Start Scenario',
    preview: 'Preview',
    difficultyEngine: 'Difficulty Engine',
    objective: 'Objective',
    constraints: 'Constraints',
    risks: 'Risks',
    sampleSituation: 'Sample Situation',
    gpridSpine: 'GPRID Spine',
    gpridTitle: 'Build step by step',
    gpridDescription:
      'Each step unlocks the next so the thinking stays traceable from goal to final answer.',
    complete: 'Complete',
    needsWork: 'Needs work',
    pending: 'Pending',
    layerReady: 'Layer is structurally ready for submission.',
    goalDesign: 'Goal Design',
    priorityDesign: 'Most Important First',
    rulesDesign: 'Rules The AI Must Follow',
    logicDesign: 'How The AI Thinks',
    decisionOutput: 'Final Answer',
    goalPlaceholder: 'Define one clear, measurable goal.',
    secondaryGoalPlaceholder: 'Optional secondary goal',
    conflictPlaceholder: 'How should the agent resolve conflicts between the top priorities?',
    addRule: 'Add Rule',
    removeRule: 'Remove rule',
    addLogicCard: 'Add Logic Card',
    removeLogicCard: 'Remove logic card',
    ruleReasoningPlaceholder: 'Why does this rule exist?',
    ifPlaceholder: 'IF condition',
    thenPlaceholder: 'THEN action',
    becausePlaceholder: 'BECAUSE reasoning',
    elsePlaceholder: 'ELSE branch',
    coordinationPlaceholder: 'Agent coordination note',
    decisionStatementPlaceholder: 'State the final decision for the sample situation',
    decisionReasoningPlaceholder:
      'Explain how the decision follows from your goal, priorities, rules, and logic.',
    lowConfidence: 'Low confidence',
    mediumConfidence: 'Medium confidence',
    highConfidence: 'High confidence',
    markGoalComplete: 'Mark Goal Complete',
    markPriorityComplete: 'Mark Priority Complete',
    markRulesComplete: 'Mark Rules Complete',
    markLogicComplete: 'Mark Logic Complete',
    markDecisionComplete: 'Mark Decision Complete',
    submitForEvaluation: 'Submit for Evaluation',
    beginnerExamples: 'Beginner Examples',
    beginnerGoal: 'Example Goal',
    beginnerPriority: 'Example Priority',
    beginnerRules: 'Example Rules',
    beginnerLogic: 'Example If-Then',
    beginnerDecision: 'Example Decision',
    evaluation: 'Evaluation',
    overallScore: 'Overall Score',
    layerBreakdown: 'Score By Step',
    strengths: 'What You Did Well',
    weaknesses: 'Needs Improvement',
    blindSpots: 'Things You Missed',
    expertRecommendation: 'How To Improve',
    evalLoadingLine1: "🤖 I'm reading your answer…",
    evalLoadingLine2: 'Checking each step…',
    evalLoadingLine3: 'This only takes a few seconds.',
    evalLoadingHint: 'Stay with me. Almost done.',
    evalCelebrationEyebrow: '🎉 Completed',
    evalCelebrationTitle: 'Well done!',
    evalCelebrationSubtitle: 'You finished the practice. Let’s learn from it.',
    evalMetaLevel: (level: string | number, label: string | number) =>
      `Level ${level} — ${label}`,
    evalMetaTrainingCode: (seed: string | number) => `Training Code ${seed}`,
    evalStep3Title: 'Overall Score',
    evalScoreMeaning: 'This score is a guide, not a label.',
    evalScenarioTitle: 'This is the scenario you answered',
    evalCoachTitle: 'AI Coach Summary',
    evalCoachFocusLabel: 'Focus first on',
    evalNoGoodThings: 'Good effort. Your strengths will show more as you retry.',
    evalImproveTitle: 'What Can Be Improved',
    evalNoImproveThings: 'No major improvements were listed for this attempt.',
    evalSuggestionsTitle: 'AI Suggestions',
    evalDeepSeekTitle: 'Extra feedback (optional)',
    evalDeepSeekDescription: 'Run an extra AI review for more examples.',
    evalDeepSeekImprovements: 'Extra suggestions',
    evalDeepSeekImprovementsFallback: 'No extra suggestions were returned yet.',
    evalDeepSeekTopTeam: 'How a top team might improve it',
    evalDeepSeekTopTeamFallback: 'No top-team examples were returned yet.',
    evalDeepSeekNotRunYet: 'You have not run the extra review yet.',
    evalTechnicalToggle: 'Show technical details (optional)',
    evalTechnicalTitle: 'Technical details',
    evalTechnicalHint: 'This is for deeper checking. You can skip it.',
    evalTechModelOverall: (value: string | number) => `Model overall: ${value}`,
    evalTechDerivedOverall: (value: string | number) =>
      `Derived overall: ${value}`,
    evalTechFinalOverall: (value: string | number) => `Final overall shown: ${value}`,
    evalBetterExampleTitle: 'Better Example Answer',
    evalBetterExampleDescription: 'See a simple before-and-after for weaker parts.',
    evalBefore: 'Before',
    evalAfter: 'After',
    evalBeforeEmpty: 'No text was found for this part.',
    evalNeedsFocus: 'Needs focus',
    evalOk: 'OK',
    evalNextActionTitle: 'Next Action',
    evalNextActionHeading: 'What should you do next?',
    evalNextActionDescription: 'Fix one weak part first. Then submit again.',
    evalFixMyAnswer: '🔄 Fix My Answer',
    evalTryNewPractice: '➡ Try New Practice',
    weakestLayerLabel: 'Weakest step: {0}',
    comparison: 'Comparison',
    previous: '{0} previous',
    pointsDelta: '{0} points',
    comparisonHint: 'Comparing this seed against your most recent prior attempt.',
    blockingIssues: '{0} blocking issues',
    coachingNotes: '{0} coaching notes',
    retrySeed: 'Retry Training Code',
    openWorkspace: 'Open Training Workspace',
    viewHistory: 'View History',
    history: 'History',
    historyTitle: 'Local attempt record',
    historyDescription:
      'Review completed attempts, filter by seed and difficulty, and replay any scenario locally without backend dependencies.',
    seedSearch: 'Seed search',
    allDomains: 'All domains',
    allLevels: 'All levels',
    noMatchingAttempts: 'No matching attempts',
    noMatchingAttemptsDescription:
      'Adjust the filters or complete a new scenario to expand your local score history.',
    viewEvaluation: 'View Evaluation',
    retryFromSeed: 'Retry from Seed',
    tutorialBanner: 'New here? Start the quick tutorial and turn on Beginner Mode for guided examples.',
    openHowToPlay: 'See How To Play',
    finishLayer: 'Complete the required fields in {0} before marking it finished.',
    layerMarked: 'Layer {0} marked complete.',
    submitFinishAll: 'Finish and mark all five layers before submitting.',
    resolveValidation: 'Resolve the remaining validation issues in {0} before submitting.',
    firstTimeBannerTitle: 'First-time onboarding',
    firstTimeBannerDescription:
      'Use the tutorial and Beginner Mode to understand the game loop before your first attempt.',
    deepseekJudge: 'DeepSeek AI Judge',
    deepseekJudgeTitle: 'Advanced AI evaluation',
    deepseekJudgeDescription:
      'Run an optional DeepSeek judging pass on top of the local rubric to get competition-style critique.',
    runDeepSeekJudge: 'Run DeepSeek Judge',
    deepseekLoading: 'DeepSeek is evaluating this submission...',
    deepseekRetry: 'Retry DeepSeek Judge',
    deepseekHistory: 'AI Judge History',
    noDeepSeekHistory: 'No DeepSeek evaluations yet for this attempt.',
    deepseekImprovements: 'How To Improve',
    deepseekTopTeam: 'How a Top Team Would Improve This',
    deepseekModel: 'Model',
    deepseekOverall: 'AI Overall',
    deepseekOptional: 'Optional advanced layer',
    deepseekErrorPrefix: 'DeepSeek error:',
    deepseekDebug: 'DeepSeek Debug',
    deepseekRawApi: 'Raw API Response',
    deepseekRawParsed: 'Parsed Response',
    deepseekFinalUi: 'Final UI Values',
    deepseekConsistency: 'Consistency Check',
    officiallyConfirmed: 'Officially Confirmed',
    reasonableAssumptions: 'Reasonable Assumptions',
    unknownInformation: 'Unknown Information',
    focusTodayLabel: 'What To Focus On Today',
    noConfirmedInfo: 'No confirmed information is listed for this item.',
    noAssumptionsInfo: 'No assumptions are included in this guide. Only official information is used.',
    noUnknownInfo: 'No unknown information is listed for this item.',
  },
  ms: {
    appTitle: 'Simulator Reka Agent',
    localMvp: 'Versi latihan semasa',
    navDashboard: 'Papan Pemuka',
    navGenerate: 'Jana',
    navWorkspace: 'Ruang Latihan',
    navHistory: 'Sejarah',
    darkMode: 'Mod gelap',
    lightMode: 'Mod cerah',
    languageEnglish: 'English',
    languageMalay: 'Bahasa Melayu',
    resume: 'Sambung',
    noActiveDraft: 'Tiada draf aktif lagi',
    resumeDescription:
      'Mulakan di Penjana Senario untuk buka satu latihan yang boleh diulang semula.',
    continueDraft: 'Sambung Latihan',
    generateScenario: 'Jana Senario',
    recentScores: 'Skor Terkini',
    latestAttempts: 'Percubaan terkini',
    openHistory: 'Buka sejarah',
    noAttemptsYet: 'Belum ada percubaan',
    noAttemptsDescription:
      'Siapkan satu latihan supaya anda boleh semak kemajuan anda dari semasa ke semasa.',
    quickStats: 'Papan Kemajuan',
    attempts: 'Jumlah Percubaan',
    average: 'Purata Skor',
    best: 'Skor Terbaik',
    weakestLayer: 'Langkah Paling Lemah',
    mostPlayedDomain: 'Domain Paling Kerap',
    historyBased: 'Berdasarkan sejarah tempatan semasa',
    nextMove: 'Langkah Seterusnya',
    practiceWeakest: 'Latih langkah paling lemah',
    practiceWeakestDescription:
      'Jana latihan baharu. Kemudian baiki bahagian {0} anda di Ruang Latihan.',
    startNewScenario: 'Mulakan Senario Baharu',
    howToPlay: 'Cara Bermain',
    howToPlayTitle: 'Fahami kitaran latihan',
    howToPlayDescription:
      'Jana satu latihan, isi lima langkah GPRID, semak maklum balas, kemudian cuba lagi.',
    howStep1: '1. Pilih bidang, tahap, dan Kod Latihan jika perlu.',
    howStep2: '2. Isi Matlamat, Keutamaan, Peraturan, Cara Berfikir, dan Jawapan Akhir ikut turutan.',
    howStep3: '3. Hantar jawapan anda dan semak bahagian paling lemah.',
    howStep4: '4. Ulang Kod Latihan yang sama untuk bandingkan kemajuan.',
    tutorialTitle: 'Selamat datang ke simulasi GPRID pertama anda',
    tutorialDescription:
      'Tutorial ringkas ini tunjuk cara simulator ini berfungsi supaya anda boleh mula dengan yakin.',
    tutorialStep1Title: '1. Mulakan Dengan Senario',
    tutorialStep1Body:
      'Pilih bidang dan tahap. Kemudian jana latihan dengan Kod Latihan yang mudah dibaca.',
    tutorialStep2Title: '2. Fikir Dalam GPRID',
    tutorialStep2Body:
      'Bina jawapan anda langkah demi langkah: Matlamat, Keutamaan, Peraturan, Cara Berfikir, dan Jawapan Akhir.',
    tutorialStep3Title: '3. Belajar Daripada Maklum Balas',
    tutorialStep3Body:
      'Hantar jawapan anda. Kemudian ulang Kod Latihan yang sama untuk lihat peningkatan.',
    tutorialDismiss: 'Faham',
    tutorialOpen: 'Buka Tutorial',
    tutorialSkip: 'Langkau Tutorial',
    beginnerMode: 'Mod Asas',
    beginnerModeHint: 'Tunjukkan contoh mudah bagi setiap langkah GPRID.',
    scenarioGenerator: 'Penjana Senario',
    scenarioGeneratorTitle: 'Cipta cabaran yang boleh diulang',
    scenarioGeneratorDescription:
      'Pilih bidang latihan, pilih tahap, dan masukkan Kod Latihan jika mahu.',
    domain: 'Bidang',
    difficulty: 'Tahap',
    seed: 'Kod Latihan',
    seedFormatHint: 'Format mudah dibaca: DOMAIN-L{0}-FAMILY-001',
    generatePreview: 'Jana Pratonton',
    newSeed: 'Kod Baharu',
    startScenario: 'Mula Senario',
    preview: 'Pratonton',
    difficultyEngine: 'Penerangan Tahap',
    objective: 'Hasil yang perlu dicapai',
    constraints: 'Perkara yang perlu dipatuhi',
    risks: 'Risiko yang perlu dijaga',
    sampleSituation: 'Contoh situasi',
    gpridSpine: 'Aliran GPRID',
    gpridTitle: 'Bina jawapan langkah demi langkah',
    gpridDescription:
      'Setiap langkah dibuka ikut turutan supaya anda nampak aliran fikirannya.',
    complete: 'Selesai',
    needsWork: 'Perlu dibaiki',
    pending: 'Belum selesai',
    layerReady: 'Langkah ini sudah sedia untuk dihantar.',
    goalDesign: 'Matlamat',
    priorityDesign: 'Keutamaan',
    rulesDesign: 'Peraturan AI',
    logicDesign: 'Cara Berfikir',
    decisionOutput: 'Jawapan Akhir',
    goalPlaceholder: 'Nyatakan hasil akhir yang anda mahu capai.',
    secondaryGoalPlaceholder: 'Matlamat tambahan jika perlu',
    conflictPlaceholder: 'Jika dua keutamaan bertembung, yang mana perlu didahulukan?',
    addRule: 'Tambah peraturan',
    removeRule: 'Buang peraturan',
    addLogicCard: 'Tambah kad langkah',
    removeLogicCard: 'Buang kad langkah',
    ruleReasoningPlaceholder: 'Kenapa peraturan ini penting?',
    ifPlaceholder: 'Jika ini berlaku',
    thenPlaceholder: 'Maka buat ini',
    becausePlaceholder: 'Sebabnya',
    elsePlaceholder: 'Jika tidak',
    coordinationPlaceholder: 'Cara agent bekerjasama',
    decisionStatementPlaceholder: 'Nyatakan keputusan akhir untuk situasi contoh',
    decisionReasoningPlaceholder:
      'Terangkan kenapa keputusan ini ikut Goal, Priority, Rules, dan Logic anda.',
    lowConfidence: 'Kurang yakin',
    mediumConfidence: 'Agak yakin',
    highConfidence: 'Sangat yakin',
    markGoalComplete: 'Tanda Matlamat Siap',
    markPriorityComplete: 'Tanda Keutamaan Siap',
    markRulesComplete: 'Tanda Peraturan Siap',
    markLogicComplete: 'Tanda Cara Berfikir Siap',
    markDecisionComplete: 'Tanda Jawapan Akhir Siap',
    submitForEvaluation: 'Hantar Jawapan',
    beginnerExamples: 'Contoh mudah',
    beginnerGoal: 'Contoh Matlamat',
    beginnerPriority: 'Contoh Keutamaan',
    beginnerRules: 'Contoh Peraturan',
    beginnerLogic: 'Contoh Cara Berfikir',
    beginnerDecision: 'Contoh Jawapan Akhir',
    evaluation: 'Penilaian',
    overallScore: 'Skor Keseluruhan',
    layerBreakdown: 'Skor Setiap Langkah',
    strengths: 'Apa Yang Anda Buat Dengan Baik',
    weaknesses: 'Apa Yang Perlu Diperbaiki',
    blindSpots: 'Apa Yang Anda Terlepas Pandang',
    expertRecommendation: 'Cara Jadi Lebih Baik',
    evalLoadingLine1: '🤖 Saya sedang baca jawapan anda…',
    evalLoadingLine2: 'Saya semak satu per satu langkah anda…',
    evalLoadingLine3: 'Ini cuma ambil sekejap.',
    evalLoadingHint: 'Tunggu ya. Hampir siap.',
    evalCelebrationEyebrow: '🎉 Tahniah',
    evalCelebrationTitle: 'Latihan berjaya disiapkan.',
    evalCelebrationSubtitle: 'Sekarang kita tengok apa yang anda boleh baiki.',
    evalMetaLevel: (level: string | number, label: string | number) =>
      `Tahap ${level} — ${label}`,
    evalMetaTrainingCode: (seed: string | number) => `Kod Latihan ${seed}`,
    evalStep3Title: 'Skor Keseluruhan',
    evalScoreMeaning: 'Skor ini cuma panduan. Bukan “cop” pada diri anda.',
    evalScenarioTitle: 'Senario yang anda jawab',
    evalCoachTitle: 'Ringkasan AI Coach',
    evalCoachFocusLabel: 'Fokus dulu pada',
    evalNoGoodThings: 'Bagus juga. Kekuatan anda akan lebih jelas bila cuba semula.',
    evalImproveTitle: 'Apa Yang Boleh Diperbaiki',
    evalNoImproveThings: 'Belum ada perkara besar yang disenaraikan untuk cubaan ini.',
    evalSuggestionsTitle: 'Cadangan AI Coach',
    evalDeepSeekTitle: 'Pandangan tambahan (pilihan)',
    evalDeepSeekDescription: 'Kalau anda mahu, jalankan semakan tambahan untuk lebih contoh.',
    evalDeepSeekImprovements: 'Cadangan tambahan',
    evalDeepSeekImprovementsFallback: 'Belum ada cadangan tambahan yang keluar lagi.',
    evalDeepSeekTopTeam: 'Contoh cara “top team” kemaskan',
    evalDeepSeekTopTeamFallback: 'Belum ada contoh “top team” yang keluar lagi.',
    evalDeepSeekNotRunYet: 'Semakan tambahan belum dijalankan lagi.',
    evalTechnicalToggle: 'Buka butiran teknikal (pilihan)',
    evalTechnicalTitle: 'Butiran teknikal',
    evalTechnicalHint: 'Bahagian ini untuk semakan mendalam. Boleh abaikan.',
    evalTechModelOverall: (value: string | number) => `Skor keseluruhan (model): ${value}`,
    evalTechDerivedOverall: (value: string | number) => `Skor keseluruhan (kiraan): ${value}`,
    evalTechFinalOverall: (value: string | number) => `Skor akhir dipaparkan: ${value}`,
    evalBetterExampleTitle: 'Contoh Jawapan Yang Lebih Baik',
    evalBetterExampleDescription: 'Lihat contoh “sebelum” dan “selepas” untuk bahagian lemah.',
    evalBefore: 'Sebelum',
    evalAfter: 'Selepas',
    evalBeforeEmpty: 'Tiada teks dijumpai untuk bahagian ini.',
    evalNeedsFocus: 'Perlu fokus',
    evalOk: 'Okey',
    evalNextActionTitle: 'Langkah Seterusnya',
    evalNextActionHeading: 'Apa anda patut buat sekarang?',
    evalNextActionDescription: 'Baiki satu bahagian dulu. Lepas itu, hantar semula.',
    evalFixMyAnswer: '🔄 Baiki Jawapan Saya',
    evalTryNewPractice: '➡ Cuba Latihan Baharu',
    weakestLayerLabel: 'Langkah paling perlu fokus: {0}',
    comparison: 'Bandingan',
    previous: '{0} sebelum ini',
    pointsDelta: '{0} mata',
    comparisonHint: 'Perbandingan ini guna Kod Latihan yang sama.',
    blockingIssues: '{0} isu penting',
    coachingNotes: '{0} nota panduan',
    retrySeed: 'Ulang Kod Latihan',
    openWorkspace: 'Buka Ruang Latihan',
    viewHistory: 'Lihat Sejarah',
    history: 'Sejarah',
    historyTitle: 'Rekod latihan anda',
    historyDescription:
      'Semak semula cubaan yang sudah siap, tapis ikut seed dan tahap, kemudian ulang mana-mana senario untuk lihat peningkatan anda.',
    seedSearch: 'Cari Kod Latihan',
    allDomains: 'Semua domain',
    allLevels: 'Semua tahap',
    noMatchingAttempts: 'Tiada percubaan sepadan',
    noMatchingAttemptsDescription:
      'Ubah penapis atau siapkan latihan baharu untuk tambah rekod anda.',
    viewEvaluation: 'Lihat Penilaian',
    retryFromSeed: 'Ulang Kod Ini',
    tutorialBanner: 'Baru mula? Buka tutorial ringkas dan hidupkan Mod Asas.',
    openHowToPlay: 'Lihat Cara Bermain',
    finishLayer: 'Lengkapkan bahagian {0} dulu sebelum tandakan siap.',
    layerMarked: 'Bahagian {0} sudah ditanda siap.',
    submitFinishAll: 'Siapkan semua lima langkah sebelum hantar.',
    resolveValidation: 'Baiki isu yang masih ada dalam {0} sebelum hantar.',
    firstTimeBannerTitle: 'Onboarding kali pertama',
    firstTimeBannerDescription:
      'Guna tutorial dan Mod Asas supaya anda faham aliran latihan pertama.',
    deepseekJudge: 'Semakan DeepSeek',
    deepseekJudgeTitle: 'Semakan AI tambahan',
    deepseekJudgeDescription:
      'Gunakan semakan ini jika anda mahu pandangan tambahan selepas semakan biasa.',
    runDeepSeekJudge: 'Semak Dengan DeepSeek',
    deepseekLoading: 'DeepSeek sedang semak jawapan anda...',
    deepseekRetry: 'Cuba Lagi Semakan DeepSeek',
    deepseekHistory: 'Sejarah semakan AI',
    noDeepSeekHistory: 'Belum ada semakan DeepSeek untuk latihan ini.',
    deepseekImprovements: 'Cara Jadi Lebih Baik',
    deepseekTopTeam: 'Cara Pasukan Terbaik Akan Baiki Jawapan Ini',
    deepseekModel: 'Model',
    deepseekOverall: 'Skor AI',
    deepseekOptional: 'Pilihan tambahan',
    deepseekErrorPrefix: 'Ralat DeepSeek:',
    deepseekDebug: 'Paparan teknikal',
    deepseekRawApi: 'Respons asal API',
    deepseekRawParsed: 'Respons selepas dibaca',
    deepseekFinalUi: 'Nilai akhir di skrin',
    deepseekConsistency: 'Semakan padanan skor',
    officiallyConfirmed: 'Disahkan Secara Rasmi',
    reasonableAssumptions: 'Andaian Munasabah',
    unknownInformation: 'Maklumat Belum Diketahui',
    focusTodayLabel: 'Fokus Hari Ini',
    noConfirmedInfo: 'Tiada maklumat disahkan disenaraikan untuk item ini.',
    noAssumptionsInfo: 'Tiada andaian dimasukkan dalam panduan ini. Hanya maklumat rasmi digunakan.',
    noUnknownInfo: 'Tiada maklumat belum diketahui disenaraikan untuk item ini.',
  },
}

export const t = (
  language: Language,
  key: string,
  ...args: Array<string | number>
): string => {
  const value = messages[language][key] ?? messages.en[key] ?? key
  const base = typeof value === 'function' ? value(...args) : String(value)
  return args.reduce<string>(
    (output, arg, index) => output.split(`{${index}}`).join(String(arg)),
    base,
  )
}
